language: node_js

node_js:
    - "10"
    - "12"
    - "14"

cache: npm

sudo: false

notifications:
    email: false

git:
    depth: 1

branches:
    only:
        - master

script:
    - yarn run test
    - yarn danger ci
